--To create table named 'EMPLOYEE'
DROP TABLE IF EXISTS EMPLOYEE

CREATE TABLE EMPLOYEE
(
EMPL_ID INT NOT NULL UNIQUE,
AGE INT NULL,
EMPL_NAME VARCHAR(50) NOT NULL,
DATE_EMPLOYED DATE DEFAULT GETDATE()
)

 --Inserting values to EMPLOYEE table

INSERT INTO EMPLOYEE
VALUES
(1,23,'ARON',' '),
(2,25,'JOHN',' '),
(3,26,'JONA',' '),
(4,27,'JOAN',' '),
(5,26,'JONNY',' '),
(6,' ','VIC',' ')

 --To create table named 'EMPL_SALARY'
DROP TABLE IF EXISTS EMPL_SALARY
CREATE TABLE EMPL_SALARY
(
EMPL_ID INT NOT NULL,
JOBTITLE VARCHAR(50) NOT NULL,
SALARY MONEY NOT NULL
)

 --Inserting values to EMPL_SALARY table
INSERT INTO EMPL_SALARY
VALUES(1,'HR',35000),
(2,'ACCOUNTANT',45000),
(3,'TYPIST',20000),
(4,'TYPIST',30000),
(5,'ANALYST',50000)

SELECT * FROM EMPLOYEE
SELECT * FROM EMPL_SALARY

 --Using GROUP BY, HAVING, ORDER BY CLAUSES 
SELECT COUNT(JOBTITLE),JOBTITLE,AVG(SALARY) AS AVGSALARY
FROM EMPL_SALARY
GROUP BY JOBTITLE
HAVING  COUNT(JOBTITLE)<3
ORDER BY COUNT(JOBTITLE) DESC

--SELECT statement with LIKE command
SELECT * FROM EMPLOYEE
WHERE EMPL_NAME LIKE 'J%N'

SELECT EMPL_ID,EMPL_NAME,AGE FROM EMPLOYEE
WHERE AGE IN(26,25) 

 --Using CASE command to employees according to their salariess
SELECT EMPL_ID,JOBTITLE,SALARY,
CASE 
   WHEN SALARY > 33000 THEN 'HIGHEST_SALARIED'
   ELSE 'LOWEST_SALARIED'
END AS SORTSALARY
FROM EMPL_SALARY
ORDER BY SORTSALARY ASC;

--Use of JOINS to join two/more tables
SELECT * /*E.EMPL_ID,E.AGE,S.JOBTITLE,S.SALARY*/
FROM EMPL_SALARY AS S
RIGHT OUTER JOIN EMPLOYEE AS E
ON E.EMPL_ID=S.EMPL_ID

--Creating a temp table to store values of the original table
DROP TABLE IF EXISTS #TEMP_EMPLOYEE
CREATE TABLE #TEMP_EMPLOYEE
(EMPL_ID INT NOT NULL,
JOBTITLE VARCHAR(50) NOT NULL,
SALARY MONEY NOT NULL
)

INSERT INTO  #TEMP_EMPLOYEE
SELECT COUNT(JOBTITLE),JOBTITLE,AVG(SALARY) AS AVGSALARY
FROM EMPL_SALARY
GROUP BY JOBTITLE
HAVING  COUNT(JOBTITLE)<3
ORDER BY COUNT(JOBTITLE) DESC

SELECT * FROM  #TEMP_EMPLOYEE



 

